# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 无名指7年的个人博客 
email: ydswcy513@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  那些年遇到的坑与解决方案
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wmz7year.com" # the base hostname & protocol for your site
github_username:  wmz7year

# Build settings
markdown: kramdown
